### ISSUE TITLE
Unable to activate knife-cloudformation-0.2.24, because sparkle_formation-0.3.0 conflicts with sparkle_formation (~> 0.2.0)

### ISSUE THREAD

**Issue by runningman84** [hw-labs/knife-cloudformation#14]
There is a conflict with the latest sparkle_formation release:
```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate knife-cloudformation-0.2.24, because sparkle_formation-0.3.0 conflicts with sparkle_formation (~> 0.2.0) (Gem::ConflictError)
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/phil/.chefdk/gem/ruby/2.1.0/gems/knife-cloudformation-0.2.24/lib/chef/knife/cloudformation_create.rb:3:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife.rb:127:in `load_commands'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife.rb:147:in `list_commands'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/application/knife.rb:198:in `print_help_and_exit'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/application/knife.rb:162:in `validate_and_parse_options'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/application/knife.rb:140:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/embedded/bin/knife:23:in `load'
        from /opt/chefdk/embedded/bin/knife:23:in `<main>'
```

**Comment by chrisroberts** [comment]
Hi! I need to update the README here. Take a look at [sfn](https://github.com/sparkleformation/sfn) which is a standalone CLI _and_ includes the `knife` plugin.

**Comment by runningman84** [comment]
ok please also document how to install the sfn tool.

**Comment by chrisroberts** [comment]
It's in the README on that repository, but the knife plugin commands are still the same.

**Comment by chrisroberts** [comment]
closing this guy up.
